# Dependencies
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "underline", "with_toc_data", "footnotes", "quote", "jekyll-paginate" ]
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Max Ammann
tagline:             'Blog'
description:         'Technical blog by Max Ammann'
url:                 maxammann.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Max Ammann
  url:               https://maxammann.org
  email:             max@maxammann.org

# Custom vars
version:             1.0.0

plugins: [ jekyll-paginate ]
