# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Max Ammann
tagline:             'Blog'
description:         'Technical blog by Max Ammann'
url:                 maxammann.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Max Ammann
  url:               https://twitter.com/mdo
  email:             maximilian.ammann@googlemail.com

# Custom vars
version:             1.0.0
