baseurl = "https://maxammann.org/"
title = "Max Ammann"
languageCode = "en-us"

# Theme to use
theme = "simple-hugo-theme"

# Pagination
paginate = 10
paginatePath = "page"

summaryLength = 30

# Copyright
copyright = "Attribution 4.0 International (CC BY 4.0)"

# Highlighting
pygmentsCodefences = true
pygmentsOptions = "linenos=true"
pygmentsStyle = "tango"
pygmentsUseClasses = true

enableGitInfo = "true"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/projects/"
    name = "projects"
    weight = 2
#  [[menu.main]]
#    url = "/galleries/"
#    name = "galleries"
#    weight = 3
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 4
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 5

  # Footer
  [[menu.footer]]
    url = "https://github.com/maxammann"
    name = "github"
    weight = 1
  [[menu.footer]]
    url = "/posts/index.xml"
    name = "rss"
    weight = 2
  [[menu.footer]]
    url = "/maxammann.asc"
    name = "gpg asc"
    weight = 3
  [[menu.footer]]
    url = "mailto:max@maxammann.org"
    name = "email"
    weight = 3


# Links format
[permalinks]
  posts = "/posts/:year/:month/:slug/"

[params]
  datefmt  = "Jan 2, 2006"
  author = "Maximilian Ammann"
  description = "Blog about technical topics like Linux, security, web development, data analysis and hardware hacking."
  genre = "Engineering"
  githubProjectUrl = "https://github.com/maxammann/blog/"