baseurl = "https://maxammann.org/"
title = "Blog by Max Ammann"
languageCode = "en-us"

# Theme to use
theme = "simple-hugo-theme"

# Pagination
paginate = 10
paginatePath = "page"

# Copyright
copyright = "Attribution 4.0 International (CC BY 4.0)"

# Highlighting
pygmentsCodefences = true
pygmentsOptions = "linenos=true"
pygmentsStyle = "tango"
pygmentsUseClasses = true

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2

  # Footer
  [[menu.footer]]
    url = "https://github.com/maxammann"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "/posts/index.xml"
    name = "RSS"
    weight = 2
  [[menu.footer]]
    url = "mailto:max@maxammann.org"
    name = "Contact"
    weight = 3


# Links format
[permalinks]
  posts = "/posts/:year/:month/:filename/"

[params]
  datefmt  = "2 Jan, 2006"

